# Build Options

set(NANOVDB_BUILD_UNITTESTS OFF)
set(NANOVDB_BUILD_EXAMPLES OFF)
set(NANOVDB_BUILD_BENCHMARK OFF)
set(NANOVDB_BUILD_DOCS OFF)
set(NANOVDB_BUILD_TOOLS OFF)
set(NANOVDB_CUDA_KEEP_PTX OFF)

set(NANOVDB_USE_CUDA OFF)
set(NANOVDB_USE_OPTIX OFF)


# External Deps Paths

file(TO_CMAKE_PATH $ENV{BOOST_ROOT} BOOST_ROOT)
file(TO_CMAKE_PATH $ENV{BOOST_INCLUDE_DIR} BOOST_INCLUDEDIR)
file(TO_CMAKE_PATH $ENV{BOOST_INCLUDE_DIR} Boost_INCLUDE_DIR)
file(TO_CMAKE_PATH $ENV{BOOST_LIBRARY_DIR} BOOST_LIBRARYDIR)

file(TO_CMAKE_PATH $ENV{TBB_ROOT} TBB_ROOT_DIR)

file(TO_CMAKE_PATH $ENV{OPENEXR_INCLUDE_DIR} OPENEXR_INCLUDE_DIR)
file(TO_CMAKE_PATH $ENV{OPENEXR_ROOT} OPENEXR_LOCATION)

file(TO_CMAKE_PATH $ENV{OPENVDB_INCLUDE_DIR} OPENVDB_INCLUDE_DIR)

set(OPENVDB_INCLUDE_DIR "${OPENVDB_INCLUDE_DIR};${OPENEXR_INCLUDE_DIR}")
