# Build Options

# NanoVDB is header-only, so only need the install target
set(NANOVDB_BUILD_UNITTESTS OFF)
set(NANOVDB_BUILD_EXAMPLES OFF)
set(NANOVDB_BUILD_BENCHMARK OFF)
set(NANOVDB_BUILD_DOCS OFF)
set(NANOVDB_BUILD_TOOLS OFF)
set(NANOVDB_CUDA_KEEP_PTX OFF)

# Do not need to include any of the dependencies because of this
set(NANOVDB_USE_OPENVDB OFF)
set(NANOVDB_USE_OPENGL OFF)
set(NANOVDB_USE_OPENCL OFF)
set(NANOVDB_USE_CUDA OFF)
set(NANOVDB_USE_TBB OFF)
set(NANOVDB_USE_BLOSC OFF)
set(NANOVDB_USE_ZLIB OFF)
set(NANOVDB_USE_OPTIX OFF)
set(NANOVDB_ALLOW_FETCHCONTENT OFF)
